### ISSUE TITLE
Downgrading from hypeAlive1.9 to hypeAlive1.8.5, white screen after comment

### ISSUE THREAD

**Issue by rahulpanwar** [hypeJunction/hypeAlive#16]
Hi,

I was using hypeAlive 1.8.5 earlier which I updated to version 1.9. Version 1.9 was not working fine so I downgrade it back to 1.8.5. But it was so sad for me that downgrade break the functionality of 1.8.5 also.
I enabled the errors from php.ini but no error found in page and console.

Will you please help me to look into this, I need it urgently.

Thanks,
Rahul

**Comment by rahulpanwar** [comment]
Hi,

I finally fixed the downgrade issue after little digging in mysql db. It might be helpful for someone.
Following classes are not defined in elgg_entity_subtypes table:
hjform 	hjForm
hjfield 	hjField
hjfile 	hjFile
hjfilefolder 	hjFileFolder
hjsegment 	hjSegment
hjannotation 	hjAnnotation
hjcategory 	hjCategory

Someone can share the mysql query for the same.

Thanks

**Comment by rahulpanwar** [comment]
Thanks Ismayil Kharedinov and hypeJunction, for hypeAlive alternate. I am planning to move on hypeInteraction, definitely with care this time ;-)

**Comment by hypeJunction** [comment]
Let me know how that goes.
I didn't have an actual database anymore, so I couldn't verify if all views
are backward compatible with hypeAlive.
